/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'generic-richtext-uploads': GenericRichtextUpload;
    users: User;
    'staged-users': StagedUser;
    roles: Role;
    teams: Team;
    accesses: Access;
    'credit-applications': CreditApplication;
    'credit-application-imports': CreditApplicationImport;
    'credit-application-assignments': CreditApplicationAssignment;
    surveys: Survey;
    'survey-results': SurveyResult;
    'satsifaction-surveys': SatsifactionSurvey;
    'login-logs': LoginLog;
    'gps-logs': GpsLog;
    'otp-logs': OtpLog;
    'recording-logs': RecordingLog;
    'recording-log-audio-files': RecordingLogAudioFile;
    'recording-log-transcriptions': RecordingLogTranscription;
    'database-locking-plugin-transaction-syncs': DatabaseLockingPluginTransactionSync;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'credit-application-imports': {
      creditApplications: 'credit-applications';
    };
  };
  collectionsSelect: {
    'generic-richtext-uploads': GenericRichtextUploadsSelect<false> | GenericRichtextUploadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'staged-users': StagedUsersSelect<false> | StagedUsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    accesses: AccessesSelect<false> | AccessesSelect<true>;
    'credit-applications': CreditApplicationsSelect<false> | CreditApplicationsSelect<true>;
    'credit-application-imports': CreditApplicationImportsSelect<false> | CreditApplicationImportsSelect<true>;
    'credit-application-assignments': CreditApplicationAssignmentsSelect<false> | CreditApplicationAssignmentsSelect<true>;
    surveys: SurveysSelect<false> | SurveysSelect<true>;
    'survey-results': SurveyResultsSelect<false> | SurveyResultsSelect<true>;
    'satsifaction-surveys': SatsifactionSurveysSelect<false> | SatsifactionSurveysSelect<true>;
    'login-logs': LoginLogsSelect<false> | LoginLogsSelect<true>;
    'gps-logs': GpsLogsSelect<false> | GpsLogsSelect<true>;
    'otp-logs': OtpLogsSelect<false> | OtpLogsSelect<true>;
    'recording-logs': RecordingLogsSelect<false> | RecordingLogsSelect<true>;
    'recording-log-audio-files': RecordingLogAudioFilesSelect<false> | RecordingLogAudioFilesSelect<true>;
    'recording-log-transcriptions': RecordingLogTranscriptionsSelect<false> | RecordingLogTranscriptionsSelect<true>;
    'database-locking-plugin-transaction-syncs': DatabaseLockingPluginTransactionSyncsSelect<false> | DatabaseLockingPluginTransactionSyncsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      DatabaseLockingPluginTransactionSyncPrune: TaskDatabaseLockingPluginTransactionSyncPrune;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generic-richtext-uploads".
 */
export interface GenericRichtextUpload {
  id: string;
  altText?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  role: string | Role;
  name: string;
  employeeId: string;
  supervisor?: (string | null) | User;
  stagedUser?: (string | null) | StagedUser;
  enableAPIKey: boolean;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions: {
    id: string;
    createdAt: string;
    expiresAt: string;
  }[];
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  name: string;
  level: 'admin' | 'manager' | 'supervisor' | 'officer';
  menus: (
    | 'user-management#viewer'
    | 'user-management#auditor'
    | 'user-management#editor'
    | 'user-management#approver'
    | 'role-management#viewer'
    | 'role-management#auditor'
    | 'role-management#editor'
    | 'role-management#approver'
    | 'team-management#viewer'
    | 'team-management#auditor'
    | 'team-management#editor'
    | 'team-management#approver'
    | 'access-management#viewer'
    | 'access-management#auditor'
    | 'access-management#editor'
    | 'access-management#approver'
    | 'credit-application-management#viewer'
    | 'credit-application-management#auditor'
    | 'credit-application-management#editor'
    | 'credit-application-management#approver'
    | 'credit-application-management#import-viewer'
    | 'credit-application-management#import-editor'
    | 'credit-application-management#import-approver'
    | 'credit-application-assignment#viewer'
    | 'credit-application-assignment#auditor'
    | 'credit-application-assignment#editor'
    | 'credit-application-assignment#approver'
    | 'survey-management#viewer'
    | 'survey-management#auditor'
    | 'survey-management#editor'
    | 'survey-management#approver'
    | 'survey-result#monitoring'
    | 'survey-result#reporting'
    | 'satisfaction-survey-management#viewer'
    | 'satisfaction-survey-management#auditor'
    | 'satisfaction-survey-management#editor'
    | 'satisfaction-survey-management#approver'
    | 'officer-task#monitoring'
    | 'officer-task#reporting'
    | 'officer-tracking#monitoring'
    | 'officer-tracking#reporting'
    | 'login-log#monitoring'
    | 'login-log#reporting'
    | 'otp-log#monitoring'
    | 'otp-log#reporting'
    | 'gps-log#monitoring'
    | 'gps-log#reporting'
    | 'recording-log#monitoring'
    | 'recording-log#reporting'
  )[];
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staged-users".
 */
export interface StagedUser {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  email: string;
  role: string | Role;
  initialPassword?: string | null;
  name: string;
  employeeId: string;
  supervisor?: (string | null) | User;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  name: string;
  supervisor: string | User;
  officers: (string | User)[];
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accesses".
 */
export interface Access {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  collection:
    | 'staged-users'
    | 'roles'
    | 'teams'
    | 'accesses'
    | 'credit-applications'
    | 'credit-application-imports'
    | 'credit-application-assignments'
    | 'surveys'
    | 'survey-results'
    | 'satisfaction-surveys'
    | 'login-logs'
    | 'gps-logs'
    | 'otp-logs'
    | 'recording-logs';
  filter:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mask:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-applications".
 */
export interface CreditApplication {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  import?: (string | null) | CreditApplicationImport;
  name: string;
  email?: string | null;
  addresses: string[];
  phoneNumbers: string[];
  whatsappNumber: string;
  smsNumber?: string | null;
  collateralRegistryName?: string | null;
  collateralName?: string | null;
  collateralDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  assetId?: string | null;
  assetName?: string | null;
  assetDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  period?: number | null;
  installment?: number | null;
  downPayment?: number | null;
  plafond?: number | null;
  vendor?: string | null;
  remarks?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  otherText1?: string | null;
  otherText2?: string | null;
  otherNumber1?: number | null;
  otherNumber2?: number | null;
  otherDate1?: string | null;
  otherDate2?: string | null;
  others?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-application-imports".
 */
export interface CreditApplicationImport {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  creditApplications?: {
    docs?: (string | CreditApplication)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-application-assignments".
 */
export interface CreditApplicationAssignment {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  creditApplication: string | CreditApplication;
  officer: string | User;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveys".
 */
export interface Survey {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-results".
 */
export interface SurveyResult {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  survey: string | Survey;
  surveyVersion: string;
  creditApplication: string | CreditApplication;
  officer: string | User;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "satsifaction-surveys".
 */
export interface SatsifactionSurvey {
  id: string;
  createdAt: string;
  createdBy?: (string | null) | User;
  updatedAt: string;
  updatedBy?: (string | null) | User;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedAt?: string | null;
  reviewedBy?: (string | null) | User;
  reviewApproved?: boolean | null;
  reviewComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs".
 */
export interface LoginLog {
  id: string;
  createdAt: string;
  ipAddress: string;
  user?: (string | null) | User;
  event: 'login' | 'logout';
  outcome?: ('success' | 'failure') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gps-logs".
 */
export interface GpsLog {
  id: string;
  createdAt: string;
  officer: string | User;
  sessionId: string;
  creditApplication?: (string | null) | CreditApplication;
  latitude: number;
  longitude: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-logs".
 */
export interface OtpLog {
  id: string;
  createdAt: string;
  creditApplication: string | CreditApplication;
  content: string;
  email?: string | null;
  whatsappNumber?: string | null;
  smsNumber?: string | null;
  emailDeliveryStatus?: ('sent' | 'failed' | 'pending') | null;
  whatsappDeliveryStatus?: ('sent' | 'failed' | 'pending') | null;
  smsDeliveryStatus?: ('sent' | 'failed' | 'pending') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-logs".
 */
export interface RecordingLog {
  id: string;
  createdAt: string;
  creditApplication: string | CreditApplication;
  officer: string | User;
  phoneNumber: string;
  audioFile?: (string | null) | RecordingLogAudioFile;
  transcription?: (string | null) | RecordingLogTranscription;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-log-audio-files".
 */
export interface RecordingLogAudioFile {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-log-transcriptions".
 */
export interface RecordingLogTranscription {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-locking-plugin-transaction-syncs".
 */
export interface DatabaseLockingPluginTransactionSync {
  id: string;
  createdAt: string;
  expiresAt: string;
  realm?: string | null;
  notified: boolean;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'staged-users';
        value: string | StagedUser;
      }
    | {
        relationTo: 'teams';
        value: string | Team;
      }
    | {
        relationTo: 'credit-application-imports';
        value: string | CreditApplicationImport;
      }
    | {
        relationTo: 'credit-applications';
        value: string | CreditApplication;
      };
  doc_users?: (string | null) | User;
  'doc_staged-users'?: (string | null) | StagedUser;
  doc_teams?: (string | null) | Team;
  'doc_credit-application-imports'?: (string | null) | CreditApplicationImport;
  'doc_credit-applications'?: (string | null) | CreditApplication;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'DatabaseLockingPluginTransactionSyncPrune';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'DatabaseLockingPluginTransactionSyncPrune') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'generic-richtext-uploads';
        value: string | GenericRichtextUpload;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'staged-users';
        value: string | StagedUser;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'accesses';
        value: string | Access;
      } | null)
    | ({
        relationTo: 'credit-applications';
        value: string | CreditApplication;
      } | null)
    | ({
        relationTo: 'credit-application-imports';
        value: string | CreditApplicationImport;
      } | null)
    | ({
        relationTo: 'credit-application-assignments';
        value: string | CreditApplicationAssignment;
      } | null)
    | ({
        relationTo: 'surveys';
        value: string | Survey;
      } | null)
    | ({
        relationTo: 'survey-results';
        value: string | SurveyResult;
      } | null)
    | ({
        relationTo: 'satsifaction-surveys';
        value: string | SatsifactionSurvey;
      } | null)
    | ({
        relationTo: 'login-logs';
        value: string | LoginLog;
      } | null)
    | ({
        relationTo: 'gps-logs';
        value: string | GpsLog;
      } | null)
    | ({
        relationTo: 'otp-logs';
        value: string | OtpLog;
      } | null)
    | ({
        relationTo: 'recording-logs';
        value: string | RecordingLog;
      } | null)
    | ({
        relationTo: 'recording-log-audio-files';
        value: string | RecordingLogAudioFile;
      } | null)
    | ({
        relationTo: 'recording-log-transcriptions';
        value: string | RecordingLogTranscription;
      } | null)
    | ({
        relationTo: 'database-locking-plugin-transaction-syncs';
        value: string | DatabaseLockingPluginTransactionSync;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generic-richtext-uploads_select".
 */
export interface GenericRichtextUploadsSelect<T extends boolean = true> {
  altText?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  role?: T;
  name?: T;
  employeeId?: T;
  supervisor?: T;
  stagedUser?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staged-users_select".
 */
export interface StagedUsersSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  email?: T;
  role?: T;
  initialPassword?: T;
  name?: T;
  employeeId?: T;
  supervisor?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  level?: T;
  menus?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  supervisor?: T;
  officers?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accesses_select".
 */
export interface AccessesSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  description?: T;
  collection?: T;
  filter?: T;
  mask?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-applications_select".
 */
export interface CreditApplicationsSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  import?: T;
  name?: T;
  email?: T;
  addresses?: T;
  phoneNumbers?: T;
  whatsappNumber?: T;
  smsNumber?: T;
  collateralRegistryName?: T;
  collateralName?: T;
  collateralDescription?: T;
  assetId?: T;
  assetName?: T;
  assetDescription?: T;
  period?: T;
  installment?: T;
  downPayment?: T;
  plafond?: T;
  vendor?: T;
  remarks?: T;
  otherText1?: T;
  otherText2?: T;
  otherNumber1?: T;
  otherNumber2?: T;
  otherDate1?: T;
  otherDate2?: T;
  others?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-application-imports_select".
 */
export interface CreditApplicationImportsSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  description?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  creditApplications?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-application-assignments_select".
 */
export interface CreditApplicationAssignmentsSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  creditApplication?: T;
  officer?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveys_select".
 */
export interface SurveysSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  description?: T;
  content?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-results_select".
 */
export interface SurveyResultsSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  survey?: T;
  surveyVersion?: T;
  creditApplication?: T;
  officer?: T;
  answers?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "satsifaction-surveys_select".
 */
export interface SatsifactionSurveysSelect<T extends boolean = true> {
  createdAt?: T;
  createdBy?: T;
  updatedAt?: T;
  updatedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  description?: T;
  content?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  reviewApproved?: T;
  reviewComment?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs_select".
 */
export interface LoginLogsSelect<T extends boolean = true> {
  createdAt?: T;
  ipAddress?: T;
  user?: T;
  event?: T;
  outcome?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gps-logs_select".
 */
export interface GpsLogsSelect<T extends boolean = true> {
  createdAt?: T;
  officer?: T;
  sessionId?: T;
  creditApplication?: T;
  latitude?: T;
  longitude?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-logs_select".
 */
export interface OtpLogsSelect<T extends boolean = true> {
  createdAt?: T;
  creditApplication?: T;
  content?: T;
  email?: T;
  whatsappNumber?: T;
  smsNumber?: T;
  emailDeliveryStatus?: T;
  whatsappDeliveryStatus?: T;
  smsDeliveryStatus?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-logs_select".
 */
export interface RecordingLogsSelect<T extends boolean = true> {
  createdAt?: T;
  creditApplication?: T;
  officer?: T;
  phoneNumber?: T;
  audioFile?: T;
  transcription?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-log-audio-files_select".
 */
export interface RecordingLogAudioFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recording-log-transcriptions_select".
 */
export interface RecordingLogTranscriptionsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-locking-plugin-transaction-syncs_select".
 */
export interface DatabaseLockingPluginTransactionSyncsSelect<T extends boolean = true> {
  createdAt?: T;
  expiresAt?: T;
  realm?: T;
  notified?: T;
  value?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  doc_users?: T;
  'doc_staged-users'?: T;
  doc_teams?: T;
  'doc_credit-application-imports'?: T;
  'doc_credit-applications'?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDatabaseLockingPluginTransactionSyncPrune".
 */
export interface TaskDatabaseLockingPluginTransactionSyncPrune {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}