export const dashboardMenuKeys = Object.freeze([
	"user-management",
	"role-management",
	"team-management",
	"credit-application-management",
	"credit-application-assignment",
	"survey-management",
	"satisfaction-survey-management",
	"officer-task",
	"officer-tracking",
	"survey-result",
	"login-activity-log",
	"otp-log",
	"gps-log",
	"recording-log"
] as const);

export const dashboardMenuLabels = Object.freeze({
	"user-management": "User Management",
	"role-management": "Role Management",
	"team-management": "Team Management",
	"credit-application-management": "Credit Application Management",
	"credit-application-assignment": "Credit Application Assignment",
	"survey-management": "Survey Management",
	"satisfaction-survey-management": "Satisfaction Survey Management",
	"officer-task": "Officer Task",
	"officer-tracking": "Officer Tracking",
	"survey-result": "Survey Result",
	"login-activity-log": "Login Activity",
	"otp-log": "OTP Log",
	"gps-log": "GPS Log",
	"recording-log": "Recording Log"
} as const);

export const dashboardRoleKeys = Object.freeze([
	"user-management#viewer",
	"user-management#auditor",
	"user-management#editor",
	"user-management#approver",
	"role-management#viewer",
	"role-management#auditor",
	"role-management#editor",
	"role-management#approver",
	"team-management#viewer",
	"team-management#auditor",
	"team-management#editor",
	"team-management#approver",
	"credit-application-management#viewer",
	"credit-application-management#auditor",
	"credit-application-management#editor",
	"credit-application-management#approver",
	"credit-application-management#import-viewer",
	"credit-application-management#import-editor",
	"credit-application-management#import-approver",
	"credit-application-assignment#viewer",
	"credit-application-assignment#auditor",
	"credit-application-assignment#editor",
	"credit-application-assignment#approver",
	"survey-management#viewer",
	"survey-management#auditor",
	"survey-management#editor",
	"survey-management#approver",
	"satisfaction-survey-management#viewer",
	"satisfaction-survey-management#auditor",
	"satisfaction-survey-management#editor",
	"satisfaction-survey-management#approver",
	"officer-task#monitoring",
	"officer-task#reporting",
	"officer-tracking#monitoring",
	"officer-tracking#reporting",
	"survey-result#monitoring",
	"survey-result#reporting",
	"login-activity-log#monitoring",
	"login-activity-log#reporting",
	"otp-log#monitoring",
	"otp-log#reporting",
	"gps-log#monitoring",
	"gps-log#reporting",
	"recording-log#monitoring",
	"recording-log#reporting"
] as const);

export const dashboardRoleLabels = Object.freeze({
	"user-management#viewer": "User Management — Viewer",
	"user-management#auditor": "User Management — Auditor",
	"user-management#editor": "User Management — Editor",
	"user-management#approver": "User Management — Approver",
	"role-management#viewer": "Role Management — Viewer",
	"role-management#auditor": "Role Management — Auditor",
	"role-management#editor": "Role Management — Editor",
	"role-management#approver": "Role Management — Approver",
	"team-management#viewer": "Team Management — Viewer",
	"team-management#auditor": "Team Management — Auditor",
	"team-management#editor": "Team Management — Editor",
	"team-management#approver": "Team Management — Approver",
	"credit-application-management#viewer": "Credit Application Management — Viewer",
	"credit-application-management#auditor": "Credit Application Management — Auditor",
	"credit-application-management#editor": "Credit Application Management — Editor",
	"credit-application-management#approver": "Credit Application Management — Approver",
	"credit-application-management#import-viewer": "Credit Application Management Import — Viewer",
	"credit-application-management#import-editor": "Credit Application Management Import — Editor",
	"credit-application-management#import-approver": "Credit Application Management Import — Approver",
	"credit-application-assignment#viewer": "Credit Application Assignment — Viewer",
	"credit-application-assignment#auditor": "Credit Application Assignment — Auditor",
	"credit-application-assignment#editor": "Credit Application Assignment — Editor",
	"credit-application-assignment#approver": "Credit Application Assignment — Approver",
	"survey-management#viewer": "Survey Management — Viewer",
	"survey-management#auditor": "Survey Management — Auditor",
	"survey-management#editor": "Survey Management — Editor",
	"survey-management#approver": "Survey Management — Approver",
	"satisfaction-survey-management#viewer": "Satisfaction Survey Management — Viewer",
	"satisfaction-survey-management#auditor": "Satisfaction Survey Management — Auditor",
	"satisfaction-survey-management#editor": "Satisfaction Survey Management — Editor",
	"satisfaction-survey-management#approver": "Satisfaction Survey Management — Approver",
	"officer-task#monitoring": "Officer Task — Monitoring",
	"officer-task#reporting": "Officer Task — Reporting",
	"officer-tracking#monitoring": "Officer Tracking — Monitoring",
	"officer-tracking#reporting": "Officer Tracking — Reporting",
	"survey-result#monitoring": "Survey Result — Monitoring",
	"survey-result#reporting": "Survey Result — Reporting",
	"login-activity-log#monitoring": "Login Activity Log — Monitoring",
	"login-activity-log#reporting": "Login Activity Log — Reporting",
	"otp-log#monitoring": "Otp Log — Monitoring",
	"otp-log#reporting": "Otp Log — Reporting",
	"gps-log#monitoring": "Gps Log — Monitoring",
	"gps-log#reporting": "Gps Log — Reporting",
	"recording-log#monitoring": "Recording Log — Monitoring",
	"recording-log#reporting": "Recording Log — Reporting"
} as const);

export const dashboardRoleSubLabels = Object.freeze({
	"user-management#viewer": "Viewer",
	"user-management#auditor": "Auditor",
	"user-management#editor": "Editor",
	"user-management#approver": "Approver",
	"role-management#viewer": "Viewer",
	"role-management#auditor": "Auditor",
	"role-management#editor": "Editor",
	"role-management#approver": "Approver",
	"team-management#viewer": "Viewer",
	"team-management#auditor": "Auditor",
	"team-management#editor": "Editor",
	"team-management#approver": "Approver",
	"credit-application-management#viewer": "Viewer",
	"credit-application-management#auditor": "Auditor",
	"credit-application-management#editor": "Editor",
	"credit-application-management#approver": "Approver",
	"credit-application-management#import-viewer": "Import Viewer",
	"credit-application-management#import-editor": "Import Editor",
	"credit-application-management#import-approver": "Import Approver",
	"credit-application-assignment#viewer": "Viewer",
	"credit-application-assignment#auditor": "Auditor",
	"credit-application-assignment#editor": "Editor",
	"credit-application-assignment#approver": "Approver",
	"survey-management#viewer": "Viewer",
	"survey-management#auditor": "Auditor",
	"survey-management#editor": "Editor",
	"survey-management#approver": "Approver",
	"satisfaction-survey-management#viewer": "Viewer",
	"satisfaction-survey-management#auditor": "Auditor",
	"satisfaction-survey-management#editor": "Editor",
	"satisfaction-survey-management#approver": "Approver",
	"officer-task#monitoring": "Monitoring",
	"officer-task#reporting": "Reporting",
	"officer-tracking#monitoring": "Monitoring",
	"officer-tracking#reporting": "Reporting",
	"survey-result#monitoring": "Monitoring",
	"survey-result#reporting": "Reporting",
	"login-activity-log#monitoring": "Monitoring",
	"login-activity-log#reporting": "Reporting",
	"otp-log#monitoring": "Monitoring",
	"otp-log#reporting": "Reporting",
	"gps-log#monitoring": "Monitoring",
	"gps-log#reporting": "Reporting",
	"recording-log#monitoring": "Monitoring",
	"recording-log#reporting": "Reporting"
} as const);

export const dashboardRoleHrefs = Object.freeze({
	"user-management#viewer": "/user-management/viewer",
	"user-management#auditor": null,
	"user-management#editor": "/user-management/editor",
	"user-management#approver": "/user-management/approver",
	"role-management#viewer": "/role-management/viewer",
	"role-management#auditor": null,
	"role-management#editor": "/role-management/editor",
	"role-management#approver": "/role-management/approver",
	"team-management#viewer": "/team-management/viewer",
	"team-management#auditor": null,
	"team-management#editor": "/team-management/editor",
	"team-management#approver": "/team-management/approver",
	"credit-application-management#viewer": "/credit-application-management/viewer",
	"credit-application-management#auditor": null,
	"credit-application-management#editor": "/credit-application-management/editor",
	"credit-application-management#approver": "/credit-application-management/approver",
	"credit-application-management#import-viewer": "/credit-application-management/import-viewer",
	"credit-application-management#import-editor": "/credit-application-management/import-editor",
	"credit-application-management#import-approver": "/credit-application-management/import-approver",
	"credit-application-assignment#viewer": "/credit-application-assignment/viewer",
	"credit-application-assignment#auditor": null,
	"credit-application-assignment#editor": "/credit-application-assignment/editor",
	"credit-application-assignment#approver": "/credit-application-assignment/approver",
	"survey-management#viewer": "/survey-management/viewer",
	"survey-management#auditor": null,
	"survey-management#editor": "/survey-management/editor",
	"survey-management#approver": "/survey-management/approver",
	"satisfaction-survey-management#viewer": "/satisfaction-survey-management/viewer",
	"satisfaction-survey-management#auditor": null,
	"satisfaction-survey-management#editor": "/satisfaction-survey-management/editor",
	"satisfaction-survey-management#approver": "/satisfaction-survey-management/approver",
	"officer-task#monitoring": "/officer-task/monitoring",
	"officer-task#reporting": "/officer-task/reporting",
	"officer-tracking#monitoring": "/officer-tracking/monitoring",
	"officer-tracking#reporting": "/officer-tracking/reporting",
	"survey-result#monitoring": "/survey-result/monitoring",
	"survey-result#reporting": "/survey-result/reporting",
	"login-activity-log#monitoring": "/login-activity-log/monitoring",
	"login-activity-log#reporting": "/login-activity-log/reporting",
	"otp-log#monitoring": "/otp-log/monitoring",
	"otp-log#reporting": "/otp-log/reporting",
	"gps-log#monitoring": "/gps-log/monitoring",
	"gps-log#reporting": "/gps-log/reporting",
	"recording-log#monitoring": "/recording-log/monitoring",
	"recording-log#reporting": "/recording-log/reporting"
} as const);

export const preferredMenuModes = Object.freeze([
	"editor",
	"viewer",
	"approver",
	"import-editor",
	"import-viewer",
	"import-approver",
	"monitoring",
	"reporting"
]);

export const dashboardMenuGroups = Object.freeze([
	["Administration", ["user-management", "role-management", "team-management"]],
	["Credit Operations", ["credit-application-management", "credit-application-assignment"]],
	["Officer Operations", ["officer-task", "officer-tracking"]],
	["Survey and Feedback", ["survey-management", "satisfaction-survey-management", "survey-result"]],
	["Security and Audit", ["login-activity-log", "otp-log", "gps-log", "recording-log"]]
] as [string, string[]][]);
